#!/bin/bash
#PBS -N IdealizedStretch
#PBS -l walltime=00:05:00
#PBS -l nodes=2:ppn=4
#PBS -q debug

cd $PBS_O_WORKDIR

module load intel

mpirun -np 2 -ppn 4 lmp_intel_cpu_intelmpi -in IdealizedStretch.lammps